return {}
-- return {
--   'Juksuu/worktrees.nvim',
--   dependencies = { 'nvim-lua/plenary.nvim', 'folke/snacks.nvim' },
--   config = function()
--     require('worktrees').setup()
--
--     vim.keymap.set('n', '<leader>gwm', function()
--       Snacks.picker.worktrees()
--     end, { desc = '[G]it: [W]orktrees [M]anager' })
--     vim.keymap.set('n', '<leader>gwc', function()
--       Snacks.picker.worktrees_new()
--     end, { desc = '[G]it: [W]orktrees [C]reate' })
--     vim.keymap.set('n', '<leader>gwd', function()
--       Snacks.picker.worktrees_remove()
--     end, { desc = '[G]it: [W]orktrees [D]elete' })
--   end,
-- }
-- return {
--   'polarmutex/git-worktree.nvim',
--   -- version = '^2',
--   branch = 'devel',
--   dependencies = { 'nvim-telescope/telescope.nvim' },
--   config = function()
--     -- vim.g.git_worktree = {
--     --   change_directory_command = "cd",
--     --   update_on_change = true,
--     --   update_on_change_command = "e .",
--     --   clearjumps_on_change = true,
--     --   confirm_telescope_deletions = true,
--     --   autopush = false,
--     -- }
--     local Hooks = require 'git-worktree.hooks'
--     local config = require 'git-worktree.config'
--     local snack_worktree = require 'snacks-worktree'
--
--     Hooks.register(Hooks.type.SWITCH, function(path, prev_path)
--       vim.notify('Moved from ' .. prev_path .. ' to ' .. path)
--       -- check if current buffer is an oil buffer
--       if vim.fn.expand('%'):find '^oil:///' then
--         -- switch to new cwd in oil
--         require('oil').open(vim.fn.getcwd())
--       else
--         -- use built in hook for non oil buffers
--         Hooks.builtins.update_current_buffer_on_switch(path, prev_path)
--       end
--     end)
--
--     Hooks.register(Hooks.type.DELETE, function()
--       vim.cmd(config.update_on_change_command)
--     end)
--     snack_worktree.pick_git_worktree()
--   end,
--   keys = {
--     {
--       '<leader>gwm',
--       function()
--         require('snacks-worktree').pick_git_worktree()
--       end,
--       desc = '[G]it [W]orktree [M]anager',
--     },
--     {
--       '<leader>gwc',
--       function()
--         require('telescope').extensions.git_worktree.create_git_worktree()
--       end,
--       desc = '[G]it [W]orktree [C]reate',
--     },
--     {
--       '<leader>gwd',
--       function()
--         require('telescope').extensions.git_worktree.delete_worktree()
--       end,
--       desc = '[G]it [W]orktree [D]elete',
--     },
--   },
-- }
